Slight improvement to ts controller test and doc
USACE/cwms-data-api pull request #569
Opened 2024-03-07 22:52 UTC by rma-rripken

verifying that we only get one point back and that it has the correct epoch millis.  And trying to better document the timezone parameter

2024-03-07 22:53 UTC, rma-rripken commented
Related to #556

2024-03-12 14:10 UTC, krowvin commented on cwms-data-api/src/main/java/cwms/cda/api/TimeSeriesController.java
> +                            + "For "+Formats.JSONV2 + " amd " + Formats.XMLV2 + " the results are returned in UTC.  "
and*

2024-03-12 15:29 UTC, MikeNeilson requested changes
Other than @krowvin 's comment about amd vs and looks good to me.

2024-03-12 17:07 UTC, MikeNeilson approved these changes

2024-03-12 17:38 UTC, merged