Feature/location levels json
USACE/cwms-data-api pull request #61
Opened 2021-10-25 18:56 UTC by rma-bryson

Initial JSON CRUD operations for Levels.

2021-10-25 19:46 UTC, MikeNeilson requested changes

2021-10-25 19:46 UTC, MikeNeilson commented on cwms_radar_api/src/main/java/cwms/radar/api/LevelsController.java
> +            String acceptHeader = ctx.req.getContentType();
Don't use the name acceptHeader here, it's not the user saying I want results in X formats. It's saying this IS the contentType.

2021-10-25 19:46 UTC, MikeNeilson commented on cwms_radar_api/src/main/java/cwms/radar/api/LevelsController.java
> +            String acceptHeader = ctx.req.getContentType();
same as above, it's NOT the acceptHeader but the actual content type of the body.

2021-10-25 19:46 UTC, MikeNeilson commented on cwms_radar_api/src/main/java/cwms/radar/api/LevelsController.java
> +        ObjectMapper om = new ObjectMapper();
this probably shouldn't have a default and should only return a mapper object for a known type and throw and exception on anything else.

2021-10-25 19:46 UTC, MikeNeilson commented on cwms_radar_api/src/main/java/cwms/radar/data/dto/LocationLevel.java
> +    private List<SeasonalValueBean> seasonalValues;
has this been tested against TimeSeries based locations levels?

2021-10-25 21:36 UTC, rma-bryson commented on cwms_radar_api/src/main/java/cwms/radar/data/dto/LocationLevel.java
> +    private List<SeasonalValueBean> seasonalValues;
yes, I tested creating a TimeSeries based location level, seasonal, and constant. I'm not sure if we want to keep the attribute properties at this point in the dto. I was told 99.99% of the time those aren't used.

2021-10-26 16:34 UTC, MikeNeilson commented on cwms_radar_api/src/main/java/cwms/radar/data/dto/LocationLevel.java
> +public class LocationLevel
this DTO isn't immutable.

2021-10-26 16:42 UTC, rma-bryson commented on cwms_radar_api/src/main/java/cwms/radar/data/dto/LocationLevel.java
> +public class LocationLevel
Updating it to be immutable with a builder to follow suit with basins and locations.

2021-10-26 19:29 UTC, rma-bryson commented on cwms_radar_api/src/main/java/cwms/radar/api/LevelsController.java
> +            String acceptHeader = ctx.req.getContentType();
updated name to reqContentType

2021-10-26 19:29 UTC, rma-bryson commented on cwms_radar_api/src/main/java/cwms/radar/api/LevelsController.java
> +            String acceptHeader = ctx.req.getContentType();
updated name to reqContentType

2021-10-26 19:29 UTC, rma-bryson commented on cwms_radar_api/src/main/java/cwms/radar/api/LevelsController.java
> +        ObjectMapper om = new ObjectMapper();
updated to only return for supported format types, else an exception is thrown.

2021-10-26 19:42 UTC, MikeNeilson commented on cwms_radar_api/src/main/java/cwms/radar/api/LevelsController.java
> +            String acceptHeader = ctx.req.getContentType();
That's a good name. Thanks.

2021-10-26 19:43 UTC, MikeNeilson approved these changes

2021-10-26 19:43 UTC, merged