Feature/ratings create
USACE/cwms-data-api pull request #63
Opened 2021-10-27 17:27 UTC by rripken

2021-10-28 17:37 UTC, MikeNeilson requested changes
Everything else looks good. Just that one I assume copy paste mishap with the exception message text.

2021-10-28 17:37 UTC, MikeNeilson commented on cwms_radar_api/src/main/java/cwms/radar/data/dao/RatingSetDao.java
> +			throw new IOException("Failed to create Rating");
This should be "retrieve rating."

2021-10-29 01:53 UTC, rripken commented on cwms_radar_api/src/main/java/cwms/radar/data/dao/RatingSetDao.java
> +			throw new IOException("Failed to create Rating");
agreed

2021-11-04 00:54 UTC, rma-rripken approved these changes

2021-11-04 01:01 UTC, rripken commented
@MikeNeilson Do you need to do something to approve your change request from before?  I fixed that a while ago but I just added some of the json support so you probably should review that too.

2021-11-04 13:36 UTC, MikeNeilson commented on build.gradle
> +ext.JAVALIN_VERSION='4.1.1'
I very much appreciate that we are actively keeping this up-to-date instead of lingering.

2021-11-04 13:36 UTC, MikeNeilson commented on cwms_radar_api/src/main/java/cwms/radar/api/Controllers.java
> +package cwms.radar.api;
This was a great idea, btw.

2021-11-04 13:41 UTC, MikeNeilson commented on cwms_radar_standalone/src/main/java/mil/army/usace/hec/RadarAPI.java
> +        .routes( () -> configureRoutes());
good change, that Javalin setup section is getting rather large.

2021-11-04 13:42 UTC, MikeNeilson approved these changes

2021-11-04 13:42 UTC, merged