Updated Water Contract Type controller to add delete functionality
USACE/cwms-data-api pull request #866
Opened 2024-09-05 22:20 UTC by zack-rma

Added delete functionality to Water Contract Type controller

2024-09-05 23:01 UTC, zack-rma commented
CDAC PR here: https://github.com/HydrologicEngineeringCenter/cwms-data-api-client/pull/222

2024-09-23 19:07 UTC, RyanM-RMA requested changes

2024-09-23 19:07 UTC, RyanM-RMA commented on cwms-data-api/src/test/java/cwms/cda/api/WaterContractTypeControllerTestIT.java
> +            .body("size()", is(0)).extract().body().as(LookupType[].class))
Remove the size check, we only care about whether it's contained in the collection.  This could, in theory, contain other lookups from other testing.

2024-09-23 19:07 UTC, RyanM-RMA commented on cwms-data-api/src/test/java/cwms/cda/api/WaterContractTypeControllerTestIT.java
> +        assertFalse(results.stream().anyMatch(r -> r.getDisplayValue().equals(CONTRACT_TYPE.getDisplayValue())));
Use `DTOMatch::assertDoesNotContain` you provide the list, the type, the identifier function (i.e. `left.getDisplayValue().equalsIgnoreCase(right.getDisplayValue)`) and a message for the assertion.

2024-09-23 19:07 UTC, RyanM-RMA commented on cwms-data-api/src/test/java/cwms/cda/api/WaterContractTypeControllerTestIT.java
> +                // ignore
Use a logger here, instead of a comment.

2024-09-23 19:07 UTC, RyanM-RMA commented on cwms-data-api/src/test/java/cwms/cda/data/dao/watersupply/WaterContractDaoTestIT.java
> +            assertTrue(retrievedType.stream().anyMatch(t -> typeMatches(t, contractType)));
use DTOMatch::assertContainsDto

2024-09-23 19:07 UTC, RyanM-RMA commented on cwms-data-api/src/test/java/cwms/cda/data/dao/watersupply/WaterContractDaoTestIT.java
> +            assertFalse(retrievedType.stream().anyMatch(t -> typeMatches(t, contractType)));
use DTOMatch::assertDoesNotContainDto

2024-09-23 21:02 UTC, zack-rma commented on cwms-data-api/src/test/java/cwms/cda/api/WaterContractTypeControllerTestIT.java
> +            .body("size()", is(0)).extract().body().as(LookupType[].class))
Removed size check

2024-09-23 21:02 UTC, zack-rma commented on cwms-data-api/src/test/java/cwms/cda/api/WaterContractTypeControllerTestIT.java
> +        assertFalse(results.stream().anyMatch(r -> r.getDisplayValue().equals(CONTRACT_TYPE.getDisplayValue())));
Used DTOMatch function, required rebase to get it

2024-09-23 21:02 UTC, zack-rma commented on cwms-data-api/src/test/java/cwms/cda/api/WaterContractTypeControllerTestIT.java
> +                // ignore
Added a logger

2024-09-23 21:03 UTC, zack-rma commented on cwms-data-api/src/test/java/cwms/cda/data/dao/watersupply/WaterContractDaoTestIT.java
> +            assertTrue(retrievedType.stream().anyMatch(t -> typeMatches(t, contractType)));
Used DTOMatch function

2024-09-23 21:03 UTC, zack-rma commented on cwms-data-api/src/test/java/cwms/cda/data/dao/watersupply/WaterContractDaoTestIT.java
> +            assertFalse(retrievedType.stream().anyMatch(t -> typeMatches(t, contractType)));
Used DTOMatch function

2024-09-23 22:08 UTC, RyanM-RMA requested changes

2024-09-23 22:08 UTC, RyanM-RMA commented on cwms-data-api/src/test/java/cwms/cda/data/dao/watersupply/WaterContractDaoTestIT.java
> +            assertTrue(retrievedType.stream().anyMatch(t -> typeMatches(t, contractType)));
You kept the assertion around, please delete that.

2024-09-23 22:08 UTC, RyanM-RMA commented on cwms-data-api/src/test/java/cwms/cda/api/WaterContractTypeControllerTestIT.java
> +    public static final Logger logger =
Rename to all caps LOGGER

2024-09-23 22:08 UTC, RyanM-RMA commented on cwms-data-api/src/test/java/cwms/cda/api/WaterContractTypeControllerTestIT.java
> +                logger.log(Level.INFO, format("Cleanup failed to delete lookup type: %s", e.getMessage()));
switch level to CONFIG

2024-09-23 22:08 UTC, RyanM-RMA commented on cwms-data-api/src/test/java/cwms/cda/api/WaterContractTypeControllerTestIT.java
> +        BiPredicate<LookupType, LookupType> match = (i, s) -> i.getDisplayValue().equals(s.getDisplayValue());
Use equalsIgnoreCase

2024-09-23 22:08 UTC, RyanM-RMA commented on cwms-data-api/src/test/java/cwms/cda/api/WaterContractTypeControllerTestIT.java
> +        BiPredicate<LookupType, LookupType> match = (i, s) -> i.getDisplayValue().equals(s.getDisplayValue());
Also, you don't need a variable for this.

2024-09-23 23:10 UTC, zack-rma commented on cwms-data-api/src/test/java/cwms/cda/data/dao/watersupply/WaterContractDaoTestIT.java
> +            assertTrue(retrievedType.stream().anyMatch(t -> typeMatches(t, contractType)));
Whoops, removed that assertion

2024-09-23 23:11 UTC, zack-rma commented on cwms-data-api/src/test/java/cwms/cda/api/WaterContractTypeControllerTestIT.java
> +    public static final Logger logger =
Renamed to LOGGER

2024-09-23 23:11 UTC, zack-rma commented on cwms-data-api/src/test/java/cwms/cda/api/WaterContractTypeControllerTestIT.java
> +                logger.log(Level.INFO, format("Cleanup failed to delete lookup type: %s", e.getMessage()));
Switched log level

2024-09-23 23:11 UTC, zack-rma commented on cwms-data-api/src/test/java/cwms/cda/api/WaterContractTypeControllerTestIT.java
> +        BiPredicate<LookupType, LookupType> match = (i, s) -> i.getDisplayValue().equals(s.getDisplayValue());
Swapped to equalsIgnoreCase and removed variable declaration

2024-09-23 23:17 UTC, RyanM-RMA approved these changes

2024-09-23 23:18 UTC, merged